name: Release
on: 
  push: 
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get release name
        id: get_release
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          RELEASE_NAME=${TAG_NAME#v}
          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV
      - name: Setup packer
        uses: hashicorp/setup-packer@v3.1.0
        with:
          version: latest
      - name: Install plugin
        run: packer plugins install github.com/hashicorp/amazon
      - name: Init
        run: packer init ./ami.pkr.hcl
      - name: Validate
        run: packer validate ./ami.pkr.hcl
      - name: Build
        id: build
        run: |
          packer build ./ami.pkr.hcl
          AMI_ID=$(jq -r '.builds[-1].artifact_id' packer-manifest.json | cut -d':' -f2)
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
      - name: Debug
        run: |
          echo "AMI: ${{ env.AMI_ID }}"
          echo "RELEASE: ${{ env.RELEASE_NAME }}"
      # - name: Restrict the oldest release
      #   run: ./.github/scripts/restrict.sh
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
      #     PRODUCT_ID: ${{ secrets.AWS_PRODUCT_ID }}
      # - name: Publish release to Marketplace
      #   run: ./.github/scripts/publish.sh
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
      #     PRODUCT_ID: ${{ secrets.AWS_PRODUCT_ID }}
      #     AMI_ID: ${{ env.AMI_ID }}
      #     ROLE_ARN: ${{ secrets.AWS_MARKETPLACE_ROLE_ARN }}
      #     RELEASE: ${{ env.RELEASE_NAME }}
